site_name: InferAdmin
site_url: https://InferAdmin.ai
repo_url: https://github.com/promptmesh/InferAdmin
repo_name: promptmesh/inferadmin
copyright: Copyright &copy; 2025 InferAdmin

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
  icon:
    logo: material/lambda
    repo: fontawesome/brands/github
  font:
    text: Inter
    code: JetBrains Mono

nav:
  - Home: index.md
  - Scope: scope.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/promptmesh
  generator: false